org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.17.3

# Mod Properties
mod_version=1.0

# more conveniently to be "local"
build_identifier=nightly
maven_group=me.lyeddie
archives_base_name=shornselines
